version: '3.8'

services:
  localstack:
    container_name: ${CONTAINER_NAME}
    image: localstack/localstack:latest
    hostname: ${CONTAINER_NAME}
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8001:8001"
    environment:
      - SERVICES=${SERVICES}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
      - DEFAULT_REGION=${AWS_REGION}
      - http_proxy=
      - https_proxy=
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "./entrypoint.d:/docker-entrypoint-initaws.d"
