server:
  servlet:
    context-path: /remittanceservice
  port: 8085

spring:
  application:
    name: remittanceserviceapi

aws:
  credentials:
    access-key: fakeAccessKeyId
    secret-key: fakeSecretAccessKey
  region:
    auto: sa-east-1
    static: sa-east-1
  dynamodb:
    endpoint: http://172.25.0.1:4566


rest:
  client:
    exchangerate:
      url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata
      service: /CotacaoDolarDia(dataCotacao=@dataCotacao)
  resources:
    remmitanceserviceapi:
      response:
        base-path-location: /remittanceservice/api/v1/remittance

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC